### ISSUE TITLE
UC04 - Classe para gerar Estoque / Produtos

### ISSUE THREAD

**Issue by regis-amaral** [regis-amaral/ProjetoRavin#13]
1 - A classe deve ser instanciada dentro da main() logo após as linhas:

    GerarFuncionarios.montaLista();
    GerarClientes.montaLista();

2 - Deverão existir duas listas, uma para armazenar o estoque e outra para armazenar apenas os produtos. A classe devera criar um produto, armazená-lo na lista de produtos e logo em seguida criar um estoque com esse produto e armazená-lo na lista de estoque:

![Image](https://user-images.githubusercontent.com/118540708/251595215-60e7e4de-b9e3-446f-8044-36aba91d7b98.png)

**Comment by regis-amaral** [comment]
@tiagospeckart implementei na issue #13 a geração de 50 produtos e suas quantidades em estoque, fiz alguns testes e acho que está ok. Poderia verificar se esqueci de algo?

**Comment by tiagospeckart** [comment]
@regis-amaral Abre uma Pull Request da tua branch da feature pra `main`, assim fica mais claro que parte do código é uma adição/modificação

**Comment by regis-amaral** [comment]
Feito!
