### ISSUE TITLE
UC07 - Refatoração da Arquitetura do Projeto

### ISSUE THREAD

**Issue by tiagospeckart** [regis-amaral/ProjetoRavin#18]
# Contexto

Conforme pegamos algumas dicas com o professor Ávila, ficou necessária criar um "template" no qual a nossa aplicação vai seguir sendo desenvolvida. O objetivo é criar o mínimo necessário para poder visualizar como seria uma arquitetura MVCS + Repository.

Vinculada com a Issue #6 

## Objetivos

- Tentar minimizar **Heranças** que poderiam se tornar **Interfaces**
- Criar hierarquias de Interfaces genéricas estendidas para interfaces mais granulares
- Criação da camada de Serviço
- Testar o fluxo de dados e Dependências entre as Classes
- Não alterar as funcionalidades já implementadas

**Comment by regis-amaral** [comment]
Acho que precisaremos finalizar a mudança da arquitetura antes de fazer um merge na master

**Comment by tiagospeckart** [comment]
Alterado destino do merge para `dev`
