### ISSUE TITLE
Ajustar dependência em ProdutoController

### ISSUE THREAD

**Issue by regis-amaral** [regis-amaral/ProjetoRavin#28]
Ajustar a classe ProdutoController para receber a injeção de dependência da classe IProdutoRepositorio

**Comment by tiagospeckart** [comment]
Desenvolvido na Issue 
- #45 
Commit [feat: Injeção de Dependência implementada em EstoqueView](https://github.com/RavinProject/ProjetoRavin/pull/45/commits/c58b03b360d42534a966954f351b24f10002a1c7)
