### ISSUE TITLE
Adoção de uma ferramenta de automação de build

### ISSUE THREAD

**Issue by tiagospeckart** [regis-amaral/ProjetoRavin#38]
Ao considerar a implementação de um teste unitário para a 
- #33 

me deparei com a necessidade de conseguir importar o JUnit para o projeto. Porém, uma escolha em frente:

Para colocar a questão para vocês, aqui está um pequeno texto (que depois irá fazer parte das nossas docs) para a gente fazer uma escolha mais informada. Apesar de eu já ter uma preferência *(rima com Cradle)*, acho importante a gente contextualizar o quê e o porquê de uma escolha. Isso irá afetar a estrutura do projeto um pouco, então é importante alguma consideração.

---

# Maven ou Gradle?

**Maven** e **Gradle** são duas ferramentas de automação de build muito utilizadas no ecossistema Java.

**Maven** é uma ferramenta mais antiga que permite gerenciar projetos Java de maneira completa, incluindo gerenciamento de dependências, geração de documentação, relatórios e controle de versão. É baseado em um arquivo XML (`pom.xml`) que define a estrutura do projeto, as dependências, plugins e outras configurações.

## Prós do Maven:
- É muito usado, portanto, tem muitos recursos disponíveis online.
- Fornece uma estrutura padrão para projetos, tornando os projetos previsíveis e fáceis de entender.
- É fácil de começar se o projeto aderir à estrutura padrão.

## Contras do Maven:
- A configuração é feita em XML, que pode ser bastante verbosa.
- O Maven é menos flexível em comparação com Gradle. Por exemplo, não oferece a possibilidade de criar tarefas customizadas com a mesma facilidade que o Gradle.
- A execução de builds complexas pode ser mais lenta em comparação com o Gradle.

**Gradle** é uma ferramenta mais recente que se destaca por ser muito flexível e poderosa. Ele permite definir tarefas customizadas e tem uma linguagem de configuração muito mais expressiva baseada em Groovy ou Kotlin.

## Prós do Gradle:
- Flexibilidade e poder para definir tarefas customizadas.
- Sintaxe mais clara e concisa, usando Groovy ou Kotlin, em vez de XML.
- Oferece a execução incremental e o daemon Gradle para acelerar o processo de build.

## Contras do Gradle:
- Embora esteja ganhando popularidade, o Gradle não é tão amplamente usado quanto o Maven, o que significa que pode haver menos recursos disponíveis online.
- A flexibilidade adicional pode tornar os projetos mais complexos e difíceis de entender para novos desenvolvedores.

**Comment by regis-amaral** [comment]
Lendo a respeito, me parece que o gradle é mais eficiente e flexível que o maven. Acho que a questão da flexibilidade permite que mantenhamos nossa própria estrutura.

https://akalankaih19.medium.com/maven-vs-gradle-a-comprehensive-comparison-for-spring-boot-developers-a04136562e#:~:text=Maven%20is%20based%20on%20a,choice%20for%20Spring%20Boot%20projects.

https://gradle.org/maven-vs-gradle/

**Comment by tiagospeckart** [comment]
Ótimo! Vou fazer um estudo de como aplicar, trabalhando na 
- #33

**Comment by tiagospeckart** [comment]
Após a refatoração, assim ficou nossa estrutura de pastas
```markdown
.
├── gradle
│   └── wrapper
└── src
    ├── main
    │   ├── java
    │   │   └── org
    │   │       └── ravin
    │   │           ├── controllers
    │   │           │   └── interfaces
    │   │           ├── dao
    │   │           │   ├── dados
    │   │           │   └── interfaces
    │   │           ├── models
    │   │           ├── services
    │   │           │   └── interfaces
    │   │           ├── utils
    │   │           │   └── enums
    │   │           └── views
    │   │               ├── cardapio
    │   │               ├── cliente
    │   │               ├── comanda
    │   │               ├── estoque
    │   │               ├── funcionario
    │   │               └── mesa
    │   └── resources
    │       └── images
    └── test
        ├── java
        │   └── org
        │       └── ravin
        │           ├── controllers
        │           ├── dao
        │           └── services
        └── resources
```

**Comment by tiagospeckart** [comment]
Gradle adotado e mudanças implementadas na `main`
