### ISSUE TITLE
Implementação Cliente Serviços

### ISSUE THREAD

**Issue by regis-amaral** [regis-amaral/ProjetoRavin#40]

**Comment by regis-amaral** [comment]
Subtarefa da issue #37

**Comment by regis-amaral** [comment]
testando comentário #40

**Comment by regis-amaral** [comment]
Teste teste #40

**Comment by regis-amaral** [comment]
Iniciando desenvolvimento

**Comment by regis-amaral** [comment]
@tiagospeckart olha com carinho, se estiver tudo ok vou realizar as alterações nas demais classes

**Comment by regis-amaral** [comment]
@tiagospeckart olha com carinho, se estiver tudo ok vou realizar as alterações nas demais classes
https://github.com/RavinProject/ProjetoRavin/pull/44

**Comment by tiagospeckart** [comment]
Merge finalizado
