### ISSUE TITLE
UC02 - Diagrama de Classe

### ISSUE THREAD

**Issue by regis-amaral** [regis-amaral/ProjetoRavin#5]
# Contexto

Já possuímos uma primeira versão do nosso Diagrama de Classes[^1], mas é crucial que façamos uma revisão cuidadosa antes de avançar com o desenvolvimento. Iremos usar a ferramenta Astah para essa tarefa [^2]. 

### Revisão
- [x] Fazer uma revisão completa do Diagrama de Classes atual, garantindo que ele representa adequadamente o domínio do problema.
- [x] Verificar se todas as classes, atributos, métodos e relacionamentos estão corretos e completos.
- [x] Identificar quaisquer inconsistências, omissões ou erros no diagrama atual.

## Atualização
- [x] Atualizar o Diagrama de Classes com base nas observações da revisão.
- [x] Adicionar, remover ou modificar classes, atributos, métodos e relacionamentos conforme necessário.
- [x] Garantir que o diagrama atualizado esteja alinhado com o modelo ER (quando estiver disponível).

# Referências
<p align="center">
  <img src="https://github.com/regis-amaral/ProjetoRavin/assets/75458110/233903bc-7fca-4450-9d19-d7e6ad93af23" width="500">
</p>

[^1]: Diagrama v1.0
[^2]: [Astah UML](https://astah.net/products/astah-uml/)

**Comment by tiagospeckart** [comment]
Cheguei a olhar o diagrama, mas chega um ponto que não adianta buscar a perfeição no planejamento. Muita coisa só teremos como ver se faz sentido ou não na hora da implementação. Vou marcar essa issue como completa, mas que ela fique aqui de referência caso alguém queira fazer mais algum comentário sobre o diagrama atual.

_E também teve o problema que não consegui instalar o Astah no meu sistema_...😅
