### ISSUE TITLE
UC03 - Alterar arquitetura para Spring Boot

### ISSUE THREAD

**Issue by regis-amaral** [regis-amaral/ProjetoRavin#6]
# Contexto

Antes de começar os trabalhos, é essencial adequarmos o projeto para um padrão arquitetural que faça sentido para este projeto, o tempo disponível e o conhecimento da equipe. Temos experiência com **MVC**[^1], mas também surgiu a possibilidade de utilizarmos a proposta do **MVCS**[^2]:
- Model
- View
- Controller
- Services

Dado que pretendemos adaptar o projeto ao framework Spring Boot após a finalização, é importante que façamos as adequações necessárias desde já.

## Subtarefas
 - #16
 - #18 

### Pesquisa
- [x] Estudar a arquitetura mínima do Spring Boot [^3] [^4]
- [x] Estudar um exemplo prático de uma codebase onde este Framework foi usado.

### Deliberação
- [x] Reunir-se como equipe para discutir e decidir sobre a abordagem de arquitetura a ser adotada.

### Desenvolvimento
- [x] Adequar a hierarquia de pacotes à nova separação de camadas, conforme a decisão tomada na deliberação.

## Notas de Rodapé
[^1]: [Devmedia - Introdução ao padrão MVC](https://www.devmedia.com.br/introducao-ao-padrao-mvc/29308)
[^2]: [Martin Fowler - Service Layer](https://martinfowler.com/eaaCatalog/serviceLayer.html)
[^3]:  [Medium - 15 boas práticas para desenvolvimento de aplicações com Spring Boot](https://medium.com/equals-lab/15-boas-pr%C3%A1ticas-para-desenvolvimento-de-aplica%C3%A7%C3%B5es-com-spring-boot-953e0ff2e24f)
[^4]: [Javapoint - Spring Boot Architecture](https://www.javatpoint.com/spring-boot-architecture)

**Comment by regis-amaral** [comment]
#7

**Comment by tiagospeckart** [comment]
Merge de #16 #18 para `dev` vai permitir proteger a `main` de possíveis códigos bugados.
